// Setting actions

export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE';
export const CHANGE_LANGUAGE_START = 'CHANGE_LANGUAGE_START';
export const CHANGE_LANGUAGE_SUCCESS = 'CHANGE_LANGUAGE_SUCCESS';
export const CHANGE_LANGUAGE_FAIL = 'CHANGE_LANGUAGE_FAIL';

export const CHANGE_SERVER = 'CHANGE_SERVER';
export const CHANGE_SERVER_START = 'CHANGE_SERVER_START';
export const CHANGE_SERVER_SUCCESS = 'CHANGE_SERVER_SUCCESS';
export const CHANGE_SERVER_FAIL = 'CHANGE_SERVER_FAIL';

export const SET_DB_VERSION = 'SET_DB_VERSION';
export const SET_DB_VERSION_START = 'SET_DB_VERSION_START';
export const SET_DB_VERSION_SUCCESS = 'SET_DB_VERSION_SUCCESS';
export const SET_DB_VERSION_FAIL = 'SET_DB_VERSION_FAIL';
