export const SET_SUMMONER_DATA = 'SET_SUMMONER_DATA'
export const SET_SUMMONER_DATA_START = 'SET_SUMMONER_DATA_START'
export const SET_SUMMONER_DATA_FAIL = 'SET_SUMMONER_DATA_FAIL'
export const SET_SUMMONER_DATA_SUCCESS = 'SET_SUMMONER_DATA_SUCCESS'