export const SET_SUMMONER_DATA = 'SET_SUMMONER_DATA'
export const SET_SUMMONER_DATA_START = 'SET_SUMMONER_DATA_START'
export const SET_SUMMONER_DATA_FAIL = 'SET_SUMMONER_DATA_FAIL'
export const SET_SUMMONER_DATA_SUCCESS = 'SET_SUMMONER_DATA_SUCCESS'

export const SET_SUMMONER_RANK = 'SET_SUMMONER_RANK'
export const SET_SUMMONER_RANK_START = 'SET_SUMMONER_RANK_START'
export const SET_SUMMONER_RANK_FAIL = 'SET_SUMMONER_RANK_FAIL'
export const SET_SUMMONER_RANK_SUCCESS = 'SET_SUMMONER_RANK_SUCCESS'